[project]
authors = [
    {name = "Rustem Yeldessov", email = "eldesov1997@gmail.com"},
]
name = "hexlet-code"
version = "0.1.0"
dependencies = [
    "flask",
    "python-dotenv",
    "gunicorn"
]
requires-python = ">=3.10"

[build-system]
requires = ["uv"]
build-backend = "setuptools.build_meta"
